
/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "stdio.h"
#include "stdint.h"
#include "drv/gpio.h"
#include "sys_clk.h"
#include "drv/pin.h"


void PIN_init(void)
{
;
}

void __attribute__ ((weak)) __ChipInitHandler(void)
{
    PIN_init();
}
